{
 "title": "MC服务器监控指标",
 "description": "MC服务器监控指标",
 "tags": [ "MC" ],
 "time": { "from": "now-2h", "to": "now" },
 "panels": [
  {
   "title": "响应时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "minecraft_status_response_time_seconds{server_version!=\"\"}",
     "legendFormat": "响应时间"
    },
    {
     "expr": "avg_over_time(minecraft_status_response_time_seconds{server_version!=\"\"}[15m])",
     "legendFormat": "平均响应时间"
    }
   ]
  },
  {
   "title": "MC内存占比",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=\"mc-server\"}\r\n/ scalar(machine_node_memory_capacity_bytes)",
     "legendFormat": "MC内存占比"
    }
   ]
  },
  {
   "title": "当前玩家数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "名" } },
   "targets": [
    {
     "expr": "minecraft_status_players_online_count{server_version!=\"\"}",
     "legendFormat": "当前玩家"
    },
    {
     "expr": "minecraft_status_players_max_count{server_version!=\"\"}",
     "legendFormat": "最大玩家"
    },
    {
     "expr": "ceil(avg_over_time(minecraft_status_players_online_count{server_version!=\"\"}[24h]))",
     "legendFormat": "平均在线玩家"
    }
   ]
  },
  {
   "title": "物理CPU核心占比",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"mc-server\"}[1m])\r\n/\r\nscalar(machine_cpu_cores)",
     "legendFormat": "物理CPU核心占比"
    }
   ]
  },
  {
   "title": "健康状态",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "minecraft_status_healthy{server_version!=\"\"}",
     "legendFormat": "健康"
    }
   ]
  }
 ]
}